### ISSUE TITLE
Question: Hosted on conda-forge for conda install

### ISSUE THREAD

**Issue by WiscEvan** [eamid/trimap#20]
Just curious, have you considered hosting trimap on [conda-forge](https://conda-forge.org/) so this could be installed via `conda install -c conda-forge trimap`?

**Comment by eamid** [comment]
Sound like a good idea! I've been mainly working on a JAX implementation. I'll open source the code soon (most likely on [google-research](https://github.com/google-research/google-research)), plus make some changes to the current code. It might be a good time to host it on conda-forge afterwards.

**Comment by WiscEvan** [comment]
Wonderful! Looking forward to it 😄

**Comment by eamid** [comment]
Hey Evan,

A JAX implementation is now available at https://github.com/google-research/google-research/tree/master/trimap. Any feedback/comments are highly appreciated!

Also, there has been a few changes in the formulation (specifically, the default hyperparams and the weighting). I will update the paper accordingly soon.
