### ISSUE TITLE
Is there any way to save the weights and parameters in the trimap for applied dataset to cluster sample data that are related to previously clustered dataset?

### ISSUE THREAD

**Issue by owlisie** [eamid/trimap#25]
Shared code really helped in research and I'd like to apply trimap to the further data analysis.
It would be great if sample data could be clustered in the same way as the deep learning network do.
What I meant is, for example, 2-dimensional cluster graph for MNIST dataset is plotted after clustering and a new image - handwritten 0-9 number maybe by my own - is set to this graph, that are contained in the right class area (0-9).
I've searched for saving and loading of K-mean cluster but no further information exists.
Actually I'm not sure weather it is possible or not.
If there's any advice for this issue, please let me know.

Thanks in advance.

**Comment by eamid** [comment]
If I understand correctly, you want to add new points to an embedding that you have already calculated? The current code does not support adding new points, but I am working on implementing an option for this. Please stay tuned, I'll keep you posted :)

**Comment by owlisie** [comment]
Glad to hear that! Thanks for consideration :D
