### ISSUE TITLE
Other Distance Metrics

### ISSUE THREAD

**Issue by shancarter** [eamid/trimap#4]
Is it possible to use something like angle (cosine similarity) as the measure of closeness?

**Comment by eamid** [comment]
Thanks for the suggestion.

Since ANNOY supports Euclidean distance, Manhattan distance, cosine distance, Hamming distance, and Dot (Inner) Product distance, it is possible to add other distance measures. I will add this soon in the next update.

**Comment by shancarter** [comment]
Awesome, thanks for the quick response!

**Comment by eamid** [comment]
I added the Manhattan, angular (i.e. cosine), and Hamming distances.

**Comment by shancarter** [comment]
Wow, thanks!
