### ISSUE TITLE
More than 2D

### ISSUE THREAD

**Issue by taylori7** [eamid/trimap#7]
This is more like a request than a problem perhaps.

Wow - I LOVE TRIMAP!! <3

Wondered if its possible to generate more than two embedded parameters already and I'm just not seeing that option? If not, any chance that could be added going forward?

Thank You and Best Wishes,
Ian

**Comment by eamid** [comment]
Thank you @taylori7 ! I am very glad you find TriMap helpful :)

You can change `n_dims` to set the number of output dimensions. I have not thoroughly tested this feature, but it seems to be working fine at least for 3D. Please let me know if you run into any bugs/issues.

Thank you,
Ehsan

**Comment by eamid** [comment]
Hi @taylori7,

Hope the comment above answered your question. I am going to close this issue for now. Let me know if you have any questions.

Thanks,
Ehsan

**Comment by eamid** [comment]
Hi @taylori7,

Hope the comment above answered your question. I am going to close this issue for now. Let me know if you have any questions.

Thanks,
Ehsan
